apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: triton-grpc
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: triton-grpc.example.com
      http:
        paths:
          - path: /inference.GRPCInferenceService/ServerLive
            pathType: Exact
            backend:
              service:
                name: triton-server
                port:
                  name: grpc
          - path: /inference.GRPCInferenceService/ServerReady
            pathType: Exact
            backend:
              service:
                name: triton-server
                port:
                  name: grpc
          - path: /inference.GRPCInferenceService/ModelReady
            pathType: Exact
            backend:
              service:
                name: triton-server
                port:
                  name: grpc
          - path: /inference.GRPCInferenceService/ServerMetadata
            pathType: Exact
            backend:
              service:
                name: triton-server
                port:
                  name: grpc
          - path: /inference.GRPCInferenceService/ModelMetadata
            pathType: Exact
            backend:
              service:
                name: triton-server
                port:
                  name: grpc
          - path: /inference.GRPCInferenceService/ModelConfig
            pathType: Exact
            backend:
              service:
                name: triton-server
                port:
                  name: grpc
          - path: /inference.GRPCInferenceService/ModelStatistics
            pathType: Exact
            backend:
              service:
                name: triton-server
                port:
                  name: grpc
          - path: /inference.GRPCInferenceService/ModelInfer
            pathType: Exact
            backend:
              service:
                name: triton-server
                port:
                  name: grpc
          - path: /inference.GRPCInferenceService/ModelStreamInfer
            pathType: Exact
            backend:
              service:
                name: triton-server
                port:
                  name: grpc
