apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - namespace.yaml
  - network_policy.yaml

patches:
  - path: replica_patch.yaml
  - path: triton_args_patch.yaml
