apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: triton-server-ingress
spec:
  podSelector:
    matchLabels:
      app: triton-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - {protocol: TCP, port: 8000}
        - {protocol: TCP, port: 8001}
        - {protocol: TCP, port: 8002}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/component: controller
      ports:
        - {protocol: TCP, port: 8000}
        - {protocol: TCP, port: 8001}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - {protocol: TCP, port: 8002}
