apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
spec:
  template:
    spec:
      containers:
        - name: triton
          args:
            - --model-repository=/models
            - --strict-model-config=true
            - --allow-metrics=true
            - --allow-gpu-metrics=true
            - --cache-config=local,size=33554432
            - --model-control-mode=explicit
            - --load-model=*
            - --log-verbose=1
