apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - ../../ingress
  - namespace.yaml
  - network_policy.yaml

patches:
  - path: replica_patch.yaml
  - path: resource_patch.yaml
  - path: ingress_http_patch.yaml
  - path: ingress_grpc_patch.yaml
  - path: triton_args_patch.yaml
