apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
spec:
  template:
    spec:
      containers:
        - name: triton
          args:
            - --model-repository=/models
            - --strict-model-config=true
            - --allow-metrics=true
            - --allow-gpu-metrics=true
            - --cache-config=local,size=16777216
            - --model-control-mode=poll
            - --repository-poll-secs=5
            - --log-verbose=2
